config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :system, only: [] do
    patch :restart
    get :wait
    get :health
  end
  resources :users do
    member { get :login }
  end
  #--------#
  # Config #
  #--------#
  namespace :config do
    resource :plex do
      member { get 'directories' }
    end
    resource :slack, only: %i[edit update create new]
    resource :the_movie_db, only: %i[edit update create new]
    resource :make_mkv, only: %i[edit update create new] do
      collection { get :install }
    end
  end
  resources :the_movie_dbs, only: %i[index] do
    collection { post 'next_page' }
  end

  #--------#
  # Movies #
  #--------#
  resources :movies do
    member do
      post :rip
      post :auto_start
      post :cancel_auto_start
    end
  end

  #----------#
  # TV Shows #
  #----------#
  resources :tvs do
    resources :seasons do
      member { post :rip }
    end
  end

  resources :disks, only: [:index] do
    member { post :eject }
  end

  resource :start
  resources :jobs, only: %i[index show]

  get 'images/:dimension/:filename', to: 'images#show', as: :image

  root to: 'start#new'
end

app/models/season.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: seasons
#
#  id              :integer          not null, primary key
#  air_date        :date
#  name            :string
#  overview        :string
#  poster_path     :string
#  season_number   :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  the_movie_db_id :integer
#  tv_id           :bigint
#
# Indexes
#
#  index_seasons_on_tv_id  (tv_id)
#
class Season < ApplicationRecord
  include Wisper::Publisher

  has_many :episodes, -> { order_by_episode_number }, dependent: :destroy, inverse_of: :season
  has_many :disk_titles, through: :episodes
  has_many :ripped_disk_titles, -> { ripped }, through: :episodes, source: :disk_titles
  belongs_to :tv

  DEFAULT_EPISODE_RUNNTIME_MARGIN = 5.minutes.to_i

  scope :order_by_season_number, -> { order(:season_number) }

  validates :season_number, presence: true

  before_save { broadcast(:season_saving, self) }
  after_commit { broadcast(:season_saved, id, async: true) }

  def season_name
    "Season #{format_season_number}"
  end

  def format_season_number
    format('%02d', season_number)
  end

  def ripped_disk_title_durations
    @ripped_disk_title_durations ||= ripped_disk_titles&.map(&:duration)&.compact_blank || []
  end

  def duration_stats
    @duration_stats ||= StatsService.call(ripped_disk_title_durations)
  end
end

app/controllers/seasons_controller.rb
# frozen_string_literal: true

class SeasonsController < ApplicationController
  def show
    @tv = Tv.includes(:ripped_disk_titles).find(params[:tv_id])
    @season = @tv.seasons.includes(
      :ripped_disk_titles,
      episodes: [
        { uploaded_video_blobs: %i[episode episode_last] }, { ripped_disk_titles: %i[episode_last] }, :video_blobs
      ]
    ).find(params[:id])
    @season.subscribe(TheMovieDb::EpisodesListener.new)
    @season.save!
    @disks = Disk.not_ejected.includes(:disk_titles)
  end

  def rip
    job = RipWorker.perform_async(disk_id: disk.id, disk_titles: rip_disk_titles)
    redirect_to job_path(job)
  end

  private

  def season
    @season ||= tv.seasons.includes(:episodes).find(params[:id])
  end

  def disk
    @disk ||= Disk.includes(disk_titles: [:episode]).find(params[:disk_id])
  end

  def tv
    @tv ||= Tv.find(params[:tv_id])
  end

  def rip_disk_titles
    disk_title_ids = []
    @rip_disk_titles ||= episode_params.filter_map do |episode_param|
      episode = season.episodes.find { _1.id == episode_param[:episode_id].to_i }
      disk_title = disk.disk_titles.find { _1.id == episode_param[:disk_title_id].to_i }
      if disk_title.episode
        disk_title.update!(video: tv, episode_last: episode)
      else
        disk_title.update!(video: tv, episode:)
      end
      next if disk_title_ids.include?(disk_title.id)

      disk_title_ids.append(disk_title.id)
      RipWorker::DiskTitleHash[{
        id: disk_title.id,
        part: episode_param[:part].presence&.to_i
      }]
    end
  end

  def episode_params
    params[:episodes].reject { _1[:episode_id].blank? || _1[:disk_title_id].blank? }.sort_by do |episode_param|
      season.episodes.find { _1.id == episode_param[:episode_id].to_i }.episode_number
    end
  end
end

app/helpers/seasons_helper.rb
# frozen_string_literal: true

module SeasonsHelper
end

app/views/seasons/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <%= link_to 'Search', root_path %>
    </li>
    <li class="breadcrumb-item">
      <%= link_to @tv.name, tv_path(@tv) %>
    </li>
    <li class="breadcrumb-item active" aria-current="page"><%= @season.name %></li>
  </ol>
</nav>
<hr/>
<%= simple_form_for :episodes, url: rip_tv_season_path(@tv, @season), class: 'pb-4', data: { controller: 'manage-selections' } do |f| %>
  <%= hidden_field_tag :disk_id, @disks.first&.id %>
  <table class="table table-hover table-responsive">
    <thead class="sticky-top bg-dark">
      <tr>
        <th></th>
        <th>Ripped</th>
        <th>Uploaded</th>
        <th>Name</th>
        <th>
          Title Select
          <small>
            <% if @tv.duration_stats.weighted_average %>
              (<%= distance_of_time_in_words(@tv.duration_range.min, 0, include_seconds: params[:debug] == 'true', scope: "datetime.distance_in_words.short") %>
              ..
              <%= distance_of_time_in_words(@tv.duration_range.max, 0, include_seconds: params[:debug] == 'true', scope: "datetime.distance_in_words.short") %>)

              <% if params[:debug] == 'true' %>
                <br>
                median: <%= distance_of_time_in_words @tv.duration_stats.median  %>
                <br>
                weighted average: <%= distance_of_time_in_words @tv.duration_stats.weighted_average  %>
                <br>
                weighted average difference: <%= distance_of_time_in_words @tv.duration_stats.weighted_average_difference %>
                <br>
                interquartile range: <%= distance_of_time_in_words(@tv.duration_stats.interquartile_range)  %>
                <br>
                median difference: <%= distance_of_time_in_words(@tv.duration_stats.median_difference)  %>
                <br>
                z score: <%= distance_of_time_in_words @tv.duration_stats.z_score %>
                <br>
                Durations: <%= @tv.ripped_disk_titles_durations.sort.uniq.join(', ') %>
                <br>
                Differences: <%= @tv.duration_stats.differences.join(', ') %>
              <% end %>
            <% end %>
          </small>
        </th>
        <th>Part</th>
      </tr>
    </thead>
    <tbody class="table-group-divider">
        <% EpisodeDiskTitleSelectorService.call(disk: @disks.first, episodes: @season.episodes).each do |title| %>
          <%= hidden_field_tag "episodes[][episode_id]", title.episode.id %>
          <tr>
            <td>
              <%= imdb_image_tag title.episode.still_path, width: 100, height: 100 %>
            </td>
            <td class="text-center">
              <h1>
                <% if title.ripped? %>
                  <%= icon('square-check') %>
                <% else %>
                  <%= icon('square') %>
                <% end %>
              </h1>
            </td>
            <td class="text-center">
              <h1>
                <% if title.uploaded? %>
                  <%= icon('square-check') %>
                <% else %>
                  <%= icon('square') %>
                <% end %>
              </h1>
            </td>

            <td>
              #<%= title.episode.episode_number %>
              <%= link_to_movie_db_episode(
                  @season.tv.the_movie_db_id,
                  @season.season_number,
                  title.episode.episode_number,
                  text: title.episode.name
                )
              %>
              <br/>
              <%= title.episode.air_date  %>
             </td>
            <td>
              <% if @disks.any? %>
                <%= select_tag 'episodes[][disk_title_id]',
                      options_from_collection_for_select(@disks.first.disk_titles.sort_by { _1.segment_map.sum }, :id, :to_label, title.disk_title&.id), prompt: "", data: { manage_selections_target: :input }, class: 'form-select mb-2' %>
              <% end %>
              <% if title.episode.duration_stats.weighted_average %>
                <%= distance_of_time_in_words(title.episode.duration_stats.weighted_average, 0) %>
              <% elsif @season.duration_stats.weighted_average%>
                <%= distance_of_time_in_words(@tv.duration_stats.weighted_average, 0) %>
              <% elsif title.episode.runtime %>
                <%= distance_of_time_in_words(title.episode.runtime, 0) %>
              <% end %>
            </td>
            <td>
              <% if @disks.any? %>
                <%= number_field_tag "episodes[][part]", nil, class: 'form-control' %>
              <% end %>
            </td>
          </tr>

        <% end %>
    </tbody>
  </table>
  <% if @disks.any? %>
    <div class='bg-dark w-100 fixed-bottom mt-1 text-right p-3 border-top'>
      <%= f.button :submit, 'Rip Disk' %>
    </div>
  <% end %>
<% end %>