config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :system, only: [] do
    patch :restart
    get :wait
    get :health
  end
  resources :users do
    member { get :login }
  end
  #--------#
  # Config #
  #--------#
  namespace :config do
    resource :plex do
      member { get 'directories' }
    end
    resource :slack, only: %i[edit update create new]
    resource :the_movie_db, only: %i[edit update create new]
    resource :make_mkv, only: %i[edit update create new] do
      collection { get :install }
    end
  end
  resources :the_movie_dbs, only: %i[index] do
    collection { post 'next_page' }
  end

  #--------#
  # Movies #
  #--------#
  resources :movies do
    member do
      post :rip
      post :auto_start
      post :cancel_auto_start
    end
  end

  #----------#
  # TV Shows #
  #----------#
  resources :tvs do
    resources :seasons do
      member { post :rip }
    end
  end

  resources :disks, only: [:index] do
    member { post :eject }
  end

  resource :start
  resources :jobs, only: %i[index show]

  get 'images/:dimension/:filename', to: 'images#show', as: :image

  root to: 'start#new'
end

app/models/config/the_movie_db.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: configs
#
#  id         :integer          not null, primary key
#  settings   :text
#  type       :string           default("Config"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Config
  class TheMovieDb < Config
    setting do |s|
      s.attribute :api_key
    end

    validates :settings_api_key, presence: true
    validate :api_key_valid

    def api_key_valid
      return if Rails.env.test? # lazy did not want to test

      ::TheMovieDb::Search::Movie.new(
        api_key: settings_api_key,
        query: 'Star Wars',
        use_cache: false
      ).results
    rescue ::TheMovieDb::Error => e
      errors.add(:settings_api_key, e.body&.dig('status_message'))
    end
  end
end

app/controllers/config/the_movie_dbs_controller.rb
# frozen_string_literal: true

class Config
  class TheMovieDbsController < ApplicationController
    before_action :set_the_movie_db, only: %i[edit update]

    def new
      @config_the_movie_db = Config::TheMovieDb.new
    end

    def edit; end

    def create
      @config_the_movie_db = Config::TheMovieDb.new(the_movie_db_params)

      if @config_the_movie_db.save
        redirect_to root_path, success: 'Created Movie DB API key'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @config_the_movie_db.update(the_movie_db_params)
        redirect_to root_path, success: 'Updated Movie DB API key'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def set_the_movie_db
      @config_the_movie_db = Config::TheMovieDb.newest
    end

    def the_movie_db_params
      params.require(:config_the_movie_db).permit(:settings_api_key)
    end
  end
end

app/controllers/the_movie_dbs_controller.rb
# frozen_string_literal: true

class TheMovieDbsController < ApplicationController
  helper_method :search_service

  def index; end

  def next_page
    respond_to do |format|
      format.html { render :index }
      format.turbo_stream
    end
  end

  private

  def search_service
    @search_service ||= VideoSearchQuery.new(**search_params)
  end

  def search_params
    params[:search]&.permit(:query, :page).to_h.symbolize_keys || {}
  end
end

app/helpers/the_movie_db_helper.rb
# frozen_string_literal: true

module TheMovieDbHelper
  HOST = 'www.themoviedb.org'

  def link_to_movie_db_seasons(tv_id, season_number, text: 'go-to the movie DB')
    link_to text, "https://#{HOST}/tv/#{tv_id}/season/#{season_number}", target: :blank
  end

  def link_to_movie_db_tv(tv_id, text: 'go-to the movie DB')
    link_to text, "https://#{HOST}/tv/#{tv_id}", target: :blank
  end

  def link_to_movie_db_movie(movie_id, text: 'go-to the movie DB')
    link_to text, "https://#{HOST}/movie/#{movie_id}", target: :blank
  end

  def link_to_movie_db_episode(tv_id, season_number, episode_number, text: 'go-to the movie DB')
    link_to text, "https://#{HOST}/tv/#{tv_id}/season/#{season_number}/episode/#{episode_number}", target: :blank
  end
end

app/views/the_movie_dbs/_next_page.html.erb
<% if search_service.next_query %>
  <div class="col-12 text-center pt-4" id="next_page" data-controller="pagination">
    <%= button_to 'Show More', next_page_the_movie_dbs_path(search: search_service.next_query), class: 'btn btn-info', data: { 'pagination-target': 'showMore', disable_with: 'Loading more...', top_offset: -8000 } %>
  </div>
<% end %>

app/views/the_movie_dbs/_video.html.erb
<div class="width-225 m-1">
  <%= link_to (video.is_a?(Tv) ? tv_path("tmdb:#{video.the_movie_db_id
  }") : movie_path("tmdb:#{video.the_movie_db_id}")), class: 'btn img-poster-btn p-1 mb-2', data: { turbo: false, disable_with: 'Loading...' } do %>
    <%= imdb_image_tag video.poster_path, klass: 'img-poster', width: 200 %>
  <% end %>

  <h6 class="card-title height-60">
    <%= video.is_a?(Tv) ? icon('tv', type: 'fas') : icon('film', type: 'fas') %>
    <% text = video.release_or_air_date ? "#{video.title} (#{video.release_or_air_date.year})" : video.title %>
    <% if video.is_a?(Tv) %>
      <%= link_to_movie_db_tv video.the_movie_db_id, text: %>
    <% else %>
      <%= link_to_movie_db_movie video.the_movie_db_id, text: %>
    <% end %>
  </h6>
</div>

app/views/the_movie_dbs/_videos.html.erb
<%= turbo_frame_tag 'videos', class: 'display-flex' do %>
  <% if params.dig(:search, :query).blank? && search_service.results.none?%>
    <div class='col-md-12'>
      <div class="text-white">
        <h1 class="display-4">To Getting Started</h1>
        <p class="lead">Type in the name of the movie or TV show your looking for into the search bar above.</p>
      </div>
    </div>
  <% end %>
  <% if search_service.results.none? && params.dig(:search, :query).present? %>
    <div class='col-md-12 text-center'>
      <div class="text-warning">
        <h4 class="display-8">No Results Found For "<%= params.dig(:search, :query) %>"</h4>
      </div>
    </div>
  <% else %>
    <%= render partial: 'video', collection: search_service.results %>
    <%= render 'next_page' %>
  <% end %>
<% end %>

app/views/the_movie_dbs/index.html.erb
<%= render SearchComponent.new(search_service:) %>
<%= render partial: 'videos', locals: { search_service: }  %>

app/views/the_movie_dbs/next_page.turbo_stream.erb
<%= turbo_stream.remove 'next_page' %>
<%= turbo_stream.append 'videos', partial: 'video', collection: search_service.results %>
<%= turbo_stream.append 'videos', partial: 'next_page' %>