config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :system, only: [] do
    patch :restart
    get :wait
    get :health
  end
  resources :users do
    member { get :login }
  end
  #--------#
  # Config #
  #--------#
  namespace :config do
    resource :plex do
      member { get 'directories' }
    end
    resource :slack, only: %i[edit update create new]
    resource :the_movie_db, only: %i[edit update create new]
    resource :make_mkv, only: %i[edit update create new] do
      collection { get :install }
    end
  end
  resources :the_movie_dbs, only: %i[index] do
    collection { post 'next_page' }
  end

  #--------#
  # Movies #
  #--------#
  resources :movies do
    member do
      post :rip
      post :auto_start
      post :cancel_auto_start
    end
  end

  #----------#
  # TV Shows #
  #----------#
  resources :tvs do
    resources :seasons do
      member { post :rip }
    end
  end

  resources :disks, only: [:index] do
    member { post :eject }
  end

  resource :start
  resources :jobs, only: %i[index show]

  get 'images/:dimension/:filename', to: 'images#show', as: :image

  root to: 'start#new'
end

app/models/job.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: jobs
#
#  id            :integer          not null, primary key
#  arguments     :text
#  backtrace     :text
#  ended_at      :datetime
#  error_class   :string
#  error_message :string
#  metadata      :text             default({}), not null
#  name          :string           not null
#  started_at    :datetime
#  status        :string           default("enqueued"), not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Job < ApplicationRecord
  STATUSES = [
    :enqueued,    # The task has been enqueued by the user.
    :running,     # The task is being performed by a job worker.
    :succeeded,   # The task finished without error.
    :cancelling,  # The task has been told to cancel but is finishing work.
    :cancelled,   # The user explicitly halted the task's execution.
    :interrupted, # The task was interrupted by the job infrastructure.
    :pausing,     # The task has been told to pause but is finishing work.
    :paused,      # The task was paused in the middle of the run by the user.
    :errored      # The task code produced an unhandled exception.
  ].freeze
  ACTIVE_STATUSES = %i[
    enqueued
    running
    paused
    pausing
    cancelling
    interrupted
  ].freeze
  STOPPING_STATUSES = %i[
    pausing
    cancelling
    cancelled
  ].freeze
  HANGING_STATUSES = %i[
    enqueued
    running
    pausing
    cancelling
  ].freeze
  COMPLETED_STATUSES = %i[succeeded errored cancelled].freeze
  enum(:status, STATUSES.index_with(&:to_s))

  serialize :arguments, coder: JSON
  serialize :backtrace, coder: YAML
  serialize :metadata, coder: JSON

  validates :name, presence: true
  validates :status, presence: true
  validates :error_message, presence: true, if: :errored?

  before_save :set_ended_at, if: :status_changed?
  before_save :set_started_at, if: :status_changed?

  scope :active, -> { where(status: ACTIVE_STATUSES) }
  scope :completed, -> { where(status: COMPLETED_STATUSES) }
  scope :problem, -> { where(status: [:errored] + HANGING_STATUSES) }
  scope :sort_by_created_at, -> { order(created_at: :desc) }
  scope :hanging, -> { where(status: HANGING_STATUSES) }

  def perform
    return unless enqueued?

    raise NotImplementedError, "#{name} must implement #perform method" unless worker.respond_to?(:perform)

    update!(status: :running)
    worker.perform
    update!(status: :succeeded)
  rescue StandardError => e
    record_exception!(e)
    broadcast_page_reload!
    nil
  end

  def name_constant
    @name_constant ||= name.constantize
  end

  def worker
    @worker ||= name_constant.new(**arguments.symbolize_keys, job: self)
  rescue StandardError => e
    record_exception!(e)
    broadcast_page_reload!
    nil
  end

  def record_exception!(exception)
    update!(
      error_message: exception.message,
      error_class: exception.class.name,
      backtrace: exception.backtrace,
      status: :errored
    )
  end

  def backtrace
    super || []
  end

  def active?
    ACTIVE_STATUSES.include?(status.to_sym) && id.present?
  end

  def add_message(message)
    return if message.blank?

    metadata['message'] ||= []
    metadata['message'] << message
    metadata['message'].compact_blank!
    message
  end

  def title=(value)
    metadata['title'] = value
  end

  def completed
    metadata['completed']
  end

  def completed=(value)
    metadata['completed'] = value.to_f
  end

  private

  def set_ended_at
    return unless COMPLETED_STATUSES.include?(status.to_sym) || STOPPING_STATUSES.include?(status.to_sym)

    self.ended_at ||= Time.current
  end

  def set_started_at
    return if status.to_sym != :running

    self.started_at ||= Time.current
  end

  def broadcast_page_reload!
    cable_ready[BroadcastChannel.channel_name].reload
    cable_ready.broadcast
  end
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

class JobsController < ApplicationController
  def index
    @jobs = Job.sort_by_created_at.limit(100)
  end

  def show
    @job = Job.find(params[:id])
    redirect_to jobs_path if @job.nil?
  end

  def load_disk; end
end

app/views/jobs/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Worker</th>
      <th scope="col">State</th>
      <th scope="col">Error Message</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <th scope="row"><%= job.id %></th>
        <th scope="row"><%= job.name %></th>
        <th><%= job.arguments %></th>
        <td><%= job.status %></td>
        <td><%= truncate job.error_message %></td>
        <td><%= link_to 'details', job_path(job), class: 'btn btn-secondary' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/show.html.erb
<% content_for :sidebar do %>
  <div class="bg-process">
    <div class="header">
      <h4>
        <%= @job.name.titleize %>
        <small class="text-muted"><%= @job.status %></small>
      </h4>
      <% if @job.started_at %>
        <div class="mb-2">
          Started At: <%= @job.started_at.to_fs(:usa_pretty)%>
        </div>
      <% end %>
    </div>
    <div class="body">
      <% metadata = @job.metadata.reject { _1 == 'message' } %>
      <% if @job.arguments.present? || metadata.present? || @job.errored? %>
        <% if @job.arguments.present? %>
          <div class="mini-console">
            <div class="console">
              <div class='title'>Arguments</div>
              <% @job.arguments.each do |key, value| %>
                <p class="pl-0"><%= key %>: <%= value %></p>
              <% end %>
            </div>
          </div>
        <% end %>

        <% if metadata.present? %>
          <div class="mini-console">
            <div class="console">
              <h5 class="title">Metadata</h5>
              <% @job.metadata.each do |key, value| %>
                <p class="pl-0"><%= key %>: <%= value %></p>
              <% end %>
            </div>
          </div>
        <% end %>

        <% if @job.errored? %>
          <div class="mini-console">
            <div class='title text-danger'>
              <%= @job.error_class %>
              <%= @job.error_message %>
            </div>
            <% if @job.backtrace.any? %>
              <div class="console">
                <% @job.backtrace.each do |trace| %>
                  <% next unless trace.include?(Rails.root.to_s) %>
                  <p><%= trace.gsub(Rails.root.to_s, 'ROOT').strip %></p>
                <% end %>
              </div>
            <% end %>
          </div>
          <% if @job.backtrace.any? %>
            <div class="mini-console">
              <div class='title'>Full Trace</div>
              <div class="console">
                <% @job.backtrace.each do |trace| %>
                  <p><%= trace.strip %></p>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      <% else %>
        No Metadata or Backtrace info to show
      <% end %>
    </div>
  </div>
<% end %>
<div class="console-content" data-controller="console">
   <%= render JobMessageComponent.new(job: @job) %>
</div>